version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USERNAME: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homework9db
